"use strict";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const CHECK_ACTIVE_USER = "CHECK_ACTIVE_USER";
export const ACTIVE_USER_CONFIRMED = "ACTIVE_USER_CONFIRMED";
export const SIGN_OUT = "BYE_BYE";

export const JOB_LISTINGS_RECEIVED = "WE_GOT_THE_JOBS";
export const BLOG_RESOURCES_RECEIVED = "WE_GOT_THE_BLOGS";

export const JOB_DATA_RECEIVED = "GOT_THE_JOB";

export const EMPLOYER_PAGE_RECEIVED = "WE_GOT_THE_JOB";

export const STREAM_OBJECT_CREATED = "AND_WE_ARE_LIVE";
export const STREAM_CLOSE = "AND_WE_ARE_CLOSED";
export const AWS_LINK_RECEIVED = "GOT_THE_LINK";
export const CLEAR_ACTIVE_LINK = "LINK_OUT";